# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Makefile for managing the infrastructure
#

#  __     __         _       _     _
#  \ \   / /_ _ _ __(_) __ _| |__ | | ___ ___
#   \ \ / / _` | '__| |/ _` | '_ \| |/ _ \ __|
#    \ V / (_| | |  | | (_| | |_) | |  __\__ \
#     \_/ \__,_|_|  |_|\__,_|_.__/|_|\___|___/
#

NAME=soccer-infrastructure
CLUSTER_NAME=soccer-us-west
ZONE=us-west1-b

#   _____                    _
#  |_   _|_ _ _ __ __ _  ___| |_ ___
#    | |/ _` | '__/ _` |/ _ \ __/ __|
#    | | (_| | | | (_| |  __/ |_\__ \
#    |_|\__,_|_|  \__, |\___|\__|___/
#                 |___/

# Create kubernetes cluster
deploy:
	gcloud deployment-manager deployments create $(NAME) --config cluster.yml

# Deletes entire deployment
clean:
	gcloud deployment-manager deployments delete $(NAME)

# Sets up the auth for kubectl k8s on the given cluster
auth:
	gcloud config set container/cluster $(CLUSTER_NAME)
	gcloud config set compute/zone $(ZONE)
	gcloud container clusters get-credentials $(CLUSTER_NAME)